apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: test-selfsigned
      - op: remove
        path: /spec/acme
      - op: add
        path: /spec/selfSigned
        value: {}
    target:
      kind: ClusterIssuer
      name: letsencrypt-prod
